### ISSUE TITLE
example doesn't seem to call mosquitto_lib_init()

### ISSUE THREAD

**Issue by wb666greene** [silentbicycle/mqtt_demo#3]
Unless I'm just old and getting senile, the demo code doesn't seem to be calling mosquitto_lib_init() function which the library documentation says must be called first.

Oversight?
I've found bad mosquittolib docs? 

I'm referring to doc at:  https://mosquitto.org/api/files/mosquitto-h.html
If this is indeed the correct documentation, may I suggest adding this link to the code comment header.

Thank you for posting this example, I always find getting to first base the most difficult part of any project.

**Comment by silentbicycle** [comment]
It's the example code that is getting old -- this is probably due to a breaking API change that happened with the mosquitto library in the four years since the example was written. The MQTT protocol itself has also changed, though mosquitto should mostly wrap that.

I added a note to the README (in d95d378) that this example is probably out of date, and not actively maintained anymore.
